module.exports = {
  SET_USER: "SET_USER",
  SIGN_OUT: "SIGN OUT",
  SHOW_MESSAGE: "[MESSAGE] SHOW MESSAGE",
  HIDE_MESSAGE: "[MESSAGE] HIDE MESSAGE",
  ADD_CHAT: "ADD_CHAT",
  CLEAR_CHAT: "CLEAR_CHAT",
  SET_USERS_LIST: 'SET_USERS_LIST',
  SET_LOADING: 'SET_LOADING'
};
